apiVersion: v2
name: headlamp
description: Headlamp is an easy-to-use and extensible Kubernetes web UI.
icon: https://raw.githubusercontent.com/headlamp-k8s/headlamp/main/docs/headlamp_light.svg
home: https://github.com/headlamp-k8s/headlamp/tree/main/deploy/helm
type: application
keywords:
  - kubernetes
  - plugins
  - kinvolk
  - headlamp
sources:
  - https://github.com/headlamp-k8s/headlamp
  - https://headlamp.dev/
maintainers:
  - name: kinvolk
    url: https://kinvolk.io/
version: 0.12.0
appVersion: 0.17.1
