apiVersion: v2
name: headlamp
description: Headlamp is an easy-to-use and extensible Kubernetes web UI.
icon: https://raw.githubusercontent.com/headlamp-k8s/headlamp/main/docs/headlamp_light.svg
home: https://headlamp.dev/
type: application
keywords:
  - kubernetes
  - plugins
  - kinvolk
  - headlamp
sources:
  - https://github.com/headlamp-k8s/headlamp/tree/main/charts/headlamp
  - https://github.com/headlamp-k8s/headlamp
maintainers:
  - name: kinvolk
    url: https://kinvolk.io/
version: 0.13.0
appVersion: 0.18.0
