name: Build and upload Mac app artifact

on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: 'Headlamp ref/branch/tag'
        required: true
        default: 'main'
      signBinaries:
        description: Notarize app
        default: true
        type: boolean
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.buildBranch }}
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: |
          app/package-lock.json
          frontend/package-lock.json
    - uses: actions/setup-go@v5
      with:
        go-version: '1.20.*'
        cache-dependency-path: |
          backend/go.sum
    - name: Dependencies
      run: brew install make
    - name: Build Backend and Frontend
      run: |
        make
    - name: Add MacOS certs
      run: cd ./app/mac/scripts/ && sh ./setup-certificate.sh
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
    - name: Build Notarized App Mac
      if: ${{ inputs.signBinaries }}
      run: |
        make app-mac
      env:
        APPLEID: ${{ secrets.APPLEID }}
        APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        APPLETEAMID: ${{ secrets.APPLETEAMID }}
    - name: Build App Mac
      if: ${{ ! inputs.signBinaries }}
      run: |
        make app-mac
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DMGs
        path: ./app/dist/Headlamp*.*
        if-no-files-found: error
        retention-days: 1
