name: Publish container
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
    inputs:
      buildTag:
        description: 'Headlamp tag (with the "v" prefix)'
        required: true
        type: string
      containerTags:
        description: 'Container tags (separated by a comma)'
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: headlamp-k8s/headlamp
jobs:
  push_to_registry:
    name: Test building container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Figure out the tag based on event trigger
      env:
        TRIGGER: ${{ github.event_name }}
      run: |
        if [ "$TRIGGER" == "workflow_dispatch" ]; then
          echo "TRIGGERED_BY_WORKFLOW_DISPATCH with build tag ${{ github.event.inputs.buildTag }}"
          BUILD_TAG=${{ github.event.inputs.buildTag }}
        else
          # on push to a tag, use the latest tag starting with v and latest as the build tag
          BUILD_TAG="$(git tag --list --sort=version:refname 'v*' | tail -1),latest"
        fi

        CONTAINER_TAGS=${{ github.event.inputs.containerTags }}
        if [ -z $CONTAINER_TAGS ]; then
          CONTAINER_TAGS=$BUILD_TAG
        fi

        # Join all tags with the image name
        TAGS=""
        for TAG in $(echo $CONTAINER_TAGS|tr ',' ' ') ; do \
          TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG},${TAGS}
        done

        # Remove trailing comma
        TAGS=$(echo $TAGS | sed s/,$//g)

        echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
        echo "CONTAINER_TAGS=$TAGS" >> $GITHUB_ENV
    - name: Print finalised tags
      run: |
        echo "BUILD_TAG=${{ env.BUILD_TAG }}"
        echo "CONTAINER_TAGS=${{ env.CONTAINER_TAGS }}"
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BUILD_TAG }}
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.CONTAINER_TAGS }}
        labels: ${{ steps.meta.outputs.labels }}
